# Generated by Django 5.0.3 on 2024-04-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2024-04-03')),
                ('end_date', models.DateField(default='2024-04-03')),
                ('category', models.ForeignKey(default='general', null=True, on_delete=django.db.models.deletion.PROTECT, to='todoapp.category')),
            ],
        ),
    ]
