# Generated by Django 5.0.3 on 2024-04-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todolist_created_alter_todolist_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['end_date']},
        ),
    ]
