# Generated by Django 5.0.3 on 2024-04-08 12:19

import todoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_todolist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='end_date',
            field=models.DateTimeField(default=todoapp.models.one_week_hence),
        ),
    ]
